#!/bin/sh

set -e

. /usr/share/debconf/confmodule

# # override the default keyring
ln -s solidrun-keyring.gpg /usr/share/keyrings/archive.gpg

# Force installation of solidrun-keyring
if ! db_get "base-installer/includes" ; then
    db_register debian-installer/dummy "base-installer/includes"
    INCLUDES="solidrun-keyring"
else
    INCLUDES="$RET solidrun-keyring"
fi
db_set base-installer/includes "$INCLUDES"

exit 0
